/// A candidate pair generated by the blocking strategy,
/// scored by the matching service.
class CandidatePair {
  /// Index of the first record
  final int index1;

  /// Index of the second record
  final int index2;

  /// Individual attribute similarity scores
  final Map<String, double> scores;

  /// Weighted overall score
  final double overallScore;

  CandidatePair({
    required this.index1,
    required this.index2,
    required this.scores,
    required this.overallScore,
  });
}
